"""Added messages table

Revision ID: 329763f17f7e
Revises: 91d6e7791082
Create Date: 2025-02-22 11:42:22.639837

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329763f17f7e'
down_revision: Union[str, None] = '91d6e7791082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('from_email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('message_text', sa.String(), nullable=True),
    sa.Column('receive_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
